# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MoneyHealth' do
  use_frameworks!

  pod 'SnapKit'
  pod 'Nuke'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for MoneyHealth

end
